// This is equivalent of saying find all the test files, and call require on each dynamically so as to make sure they are all within the bundle generated by tests.

let testContext = (<{ context?: Function }>require).context('./', true, /\.test\.ts/);
testContext.keys().forEach(testContext);
