export const UserActionType = {
  GET_COMPONENT_DATA: 'GET_COMPONENT_DATA',
  SELECT_NODE: 'SELECT_NODE',
  SEARCH_NODE: 'SEARCH_NODE'
};

export const BackendActionType = {
  COMPONENT_DATA_CHANGED: 'COMPONENT_DATA_CHANGED'
};