export const UserActionType = {
  START_COMPONENT_TREE_INSPECTION: 'START_COMPONENT_TREE_INSPECTION',
  SELECT_NODE: 'SELECT_NODE',
  SEARCH_NODE: 'SEARCH_NODE'
};

export const BackendActionType = {
  COMPONENT_TREE_CHANGED: 'COMPONENT_TREE_CHANGED'
};
